### ISSUE TITLE
Missing webpack-stats on setup?

### ISSUE THREAD

**Issue by nathunsmitty** [daily-bruin/kerckhoff#43]
Tried setting up Kerckhoff for the first time and I got this error after running `docker-compose up`:
![screen shot 2018-05-31 at 10 11 25 am](https://user-images.githubusercontent.com/5677971/40796839-2ed84d4c-64bb-11e8-9e91-dc59edf5dddb.png)

I noticed that `webpack-stats.json` is in both `.gitignore` and `.dockerignore`. I'm not familiar with it, but I would assume that it needs to be autogenerated by webpack? Why then was it not autogenerated on my machine during setup? I'm guessing what's happening is it's looking for `webpack-stats.json` before webpack runs?

**Comment by hongee** [comment]
we changed the way we build frontend on dev cos its causing a lot of problems between osx/windows - so this is no longer automated but instead you'll need to run `npm run watch` locally to build the package dependencies. For production it is still built automatically

**Comment by nathunsmitty** [comment]
So run `npm run watch` before `docker-compose up`?

**Comment by hongee** [comment]
you can run it whenever - once that's ran the error will disappear

**Comment by nathunsmitty** [comment]
Do the `node_modules` need to be installed locally also, i.e., do I need to run `npm install`?

**Comment by hongee** [comment]
yeap

**Comment by nathunsmitty** [comment]
aite add documentation in #42
